// <auto-generated />
namespace Data.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class urlstoragev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlstoragev1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010261422154_url-storage-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
